# Introduction to Numpy

NumPy, which stands for Numerical Python, is a fundamental library for scientific computing in Python. It provides powerful tools for working with numerical data, including

In [ ]:
import numpy as np

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
# Range
np2 = np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Step 
np3 = np.arange(0, 10, 2)
np3

array([0, 2, 4, 6, 8])

In [5]:
# Zeroes
np4 = np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Ones
np5  = np.ones(10)
np5


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np6  = np.full(10, 6)
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [ ]:
# multi-dimensional
np6  = np.full((2,6), 6)
np6

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [12]:
array = [1,2,3,4,5,6]
np7 = np.array(array)
np7

array([1, 2, 3, 4, 5, 6])

### Slicing Numpy array

In [ ]:
my_np1= np.array([1,2,3,4,-5,6,7,8,9])

# Slicing
print(my_np1[1:5])
print(my_np1[3:])
print(my_np1[:3])
print(my_np1[::2])
print(my_np1[::-1])


[2 3 4 5]
[4 5 6 7 8 9]
[1 2 3]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [24]:
from numpy.random import randn
my_np2 = np.random.randint(9,size=(2,4))
my_np2

array([[2, 8, 1, 1],
       [1, 2, 5, 6]])

In [28]:
# Slice 2d-array 
print(my_np2[:1, 1:3])

[[8 1]]


In [32]:
print(my_np1)
print("Square Root: ", np.sqrt(my_np1))
print("Absolute: ", np.absolute(my_np1))
print("Exponents: ", np.exp(my_np1))
print("Min Value: ", np.min(my_np1))
print("Max Value: ", np.max(my_np1))


[1 2 3 4 5 6 7 8 9]
Square Root:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
Absolute:  [1 2 3 4 5 6 7 8 9]
Exponents:  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
Min Value:  1
Max Value:  9


### Shape and Reshape nparray

In [36]:
my_np3 = np.random.randint(12,size=(12))

print(my_np3)
my_np4= my_np3.reshape(2,3,2)
print(my_np4)
print(my_np4.shape)


[ 5 10 10  1 10  9  4  3  7 11  3  3]
[[[ 5 10]
  [10  1]
  [10  9]]

 [[ 4  3]
  [ 7 11]
  [ 3  3]]]
(2, 3, 2)


In [38]:
my_np5 = my_np4.reshape(-1)
my_np5

array([ 5, 10, 10,  1, 10,  9,  4,  3,  7, 11,  3,  3])

### Indexing through ndarray

In [39]:
my_np6 = np.random.randint(12,size=(3,3,3))
my_np6

array([[[10,  8,  0],
        [ 5,  8,  5],
        [11, 11, 11]],

       [[ 9,  3,  9],
        [ 2,  1,  2],
        [10,  4,  6]],

       [[ 9,  4,  9],
        [ 5,  5,  9],
        [ 4,  0, 11]]])

In [ ]:

for x in np.nditer(my_np6):
    print(x, end=" ")
    

10 8 0 5 8 5 11 11 11 9 3 9 2 1 2 10 4 6 9 4 9 5 5 9 4 0 11 

### Sorting the ndarray

In [43]:
my_np7 = np.random.randint(12, size=(6))
my_np7

array([10,  2, 10, 11,  3,  2])

In [44]:
print(np.sort(my_np7))

[ 2  2  3 10 10 11]


In [45]:
my_np8 = np.array(["Jay-z","2-pac", "Naaz", "Zindney"])
print(np.sort(my_np8))

['2-pac' 'Jay-z' 'Naaz' 'Zindney']
