### Vectors in Numpy

In [2]:
import numpy as np


# Math for Machine Learning


In [3]:
x = np.array([25, 2, 5])

In [4]:
len(x)

3

In [5]:
x.shape

(3,)

In [6]:
type(x)

numpy.ndarray

In [7]:
type(x[0])

numpy.int64

### Vector Transposition

In [8]:
# Transposing one dimensional array has no effect...
x_t = x.T
x_t.shape

(3,)

In [9]:
# In a 2d array
y = np.array([[1, 3, 4 ,5]])
y_t = y.T
y_t

array([[1],
       [3],
       [4],
       [5]])

### Vectors in Pytorch and TensorFlow

In [10]:
# TensorFlow
import tensorflow as tf
print(tf.__version__)

# PyTorch
import torch
print(torch.__version__)

2.17.0
2.5.1


In [11]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [12]:
x_tf = tf.Variable([25, 2, 6])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  6], dtype=int32)>

## L<sup>2</sup> Norm

In [13]:
x

array([25,  2,  5])

In [14]:
(25**2 + 2**2 + 5**2) ** (1/2)

25.573423705088842

In [15]:
np.linalg.norm(x)

25.573423705088842

### L<sup>1</sup> Norm

l<sup>1</sup> = Summation of all |x<sub>i</sub>|

In [16]:
np.abs(25) + np.abs(2) + np.abs(5)

32

### Max Norm 

In [17]:
x

array([25,  2,  5])

In [18]:
np.max([np.abs(25), np.abs(2), np.max(5)])

25

### Orthogonal Vectors

In [19]:
x= np.array([1,0])
y= np.array([0,1])

np.dot(x,y)

0