## Matrices (Rank 2 Tensors) in Numpy

In [1]:
import numpy as np


In [3]:
# Use array() with nested brackets
x=np.array([[25, 2], [5,26], [3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
# accessed all the second elements of all rows
x[:,1] #rows and columns

array([ 2, 26,  7])

In [ ]:
# Select the middle row
x[1,:]

array([ 5, 26])

In [12]:
# Slicing by index
x[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

### Matrices in Pytorch

In [13]:
# TensorFlow
import tensorflow as tf
print(tf.__version__)

# PyTorch
import torch
print(torch.__version__)


2.17.0
2.5.1


In [15]:
x_pt = torch.tensor([[25, 2], [5,26], [3,7]])
x_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [17]:
x_pt[1,:] # very much pythonic

tensor([ 5, 26])

### Matrices in TensorFlow


In [19]:
x_tf = tf.Variable([[25, 2], [5,26], [3,7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>