# Higher Rank Tensors
As a example, rank 4 tensors are common for images, where each dimension corresponds to:
1. Number of images in training batch e.g 32
2. Image height in pixels e.g 28 for MNIST digits
3. Image width in pixels
4. Number of colours channels eg: 3 for full color images

In [2]:
# Numpy 
import numpy as np

# TensorFlow
import tensorflow as tf
print(tf.__version__)

# PyTorch
import torch
print(torch.__version__)

2.17.0
2.5.1


In [3]:
images_pt = torch.zeros([32, 28, 28, 3])

In [4]:
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

### Tensor Operations

##### 1. Tensor Tranposition

In [4]:
x = np.array([[25, 2],[2, 26], [6,7]])

In [ ]:

x.T

array([[25,  2,  6],
       [ 2, 26,  7]])

In [6]:
# tf
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[25,  2,  6],
       [ 2, 26,  7]])>

### Basic Tensor Arithmetic

In [7]:
x*2

array([[50,  4],
       [ 4, 52],
       [12, 14]])

In [8]:
x+2

array([[27,  4],
       [ 4, 28],
       [ 8,  9]])

In [9]:
x*2+2


array([[52,  6],
       [ 6, 54],
       [14, 16]])

### Hadamard Product or Element wise Product

The Hadamard product is a binary operation in mathematics that multiplies two matrices of the same dimensions element-wise to produce a new matrix

eg: A ⊙ A<sup>T</sup>

In [11]:
A = x+2
A

array([[27,  4],
       [ 4, 28],
       [ 8,  9]])

In [12]:
x * A

array([[675,   8],
       [  8, 728],
       [ 48,  63]])

### Reduction Operation


In [13]:
x

array([[25,  2],
       [ 2, 26],
       [ 6,  7]])

In [14]:
x.sum()

68

In [17]:
x_pt = torch.tensor([[25, 2], [5,26], [3,7]])
torch.sum(x_pt)

tensor(68)

In [18]:
x_tf = tf.Variable([[25, 2], [5,26], [3,7]])
tf.reduce_sum(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [20]:
print(x.sum(axis=0))
print(x.sum(axis=1))

[33 35]
[27 28 13]


In [21]:
torch.sum(x_pt,0)

tensor([33, 35])

In [22]:
tf.reduce_sum(x_tf, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10], dtype=int32)>

Many operations can be applied with reduction along all or a selection of axes, eg:
* maximum 
* minimum 
* mean 
* product


## The Dot Product

If we have two vectors(say x and y) with the same length n, we can calculate the dot product between them:
* x.y
* x<sup>T</sup> y
* <x,y>

In [25]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [26]:
y = np.array([2,3,4])
y

array([2, 3, 4])

In [28]:
1*2 + 2*3 + 3*4

20

In [29]:
np.dot(x,y)

20

In [30]:
x1=[[1,2,3],[2,3,4],[3,4,5]]
y1=[[2,4,6],[8,10,12],[14,16,18]]
np.dot(x1,y1)

array([[ 60,  72,  84],
       [ 84, 102, 120],
       [108, 132, 156]])