# Matrix Properties

### Forbenius Norm

In [32]:
import numpy as np

# TensorFlow
import tensorflow as tf
print(tf.__version__)

# PyTorch
import torch
print(torch.__version__)

2.17.0
2.5.1


In [33]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [34]:
# Calculating Forbenius Norm
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [35]:
np.linalg.norm(x)

5.477225575051661

### Matrix Multiplication

In [36]:
A = np.array([[3, 4],[5, 6],[7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [37]:
b = np.array([1,2])
b

array([1, 2])

In [38]:
np.dot(A,b)

array([11, 17, 23])

In [39]:
A_pt = torch.tensor([[3, 4],[5, 6],[7, 8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [40]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [41]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [42]:
A_tf = tf.Variable([[3, 4],[5, 6],[7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [43]:
b_tf = tf.Variable([1,2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [44]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

In [45]:
b1 = np.array([[1,2],[9,0]])

In [46]:
# Matrix by Matrix Multiplication
np.dot(A, b1)  #3:2 x 2:2 -> 3:2

array([[39,  6],
       [59, 10],
       [79, 14]])

In [47]:
b1_pt = torch.from_numpy(b1)
b1_pt

tensor([[1, 2],
        [9, 0]])

In [48]:
torch.matmul(A_pt, b1_pt)

tensor([[39,  6],
        [59, 10],
        [79, 14]])

In [49]:
b1_tf = tf.convert_to_tensor(b1, dtype=tf.int32)
b1_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [9, 0]], dtype=int32)>

In [50]:
tf.matmul(A_tf, b1_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[39,  6],
       [59, 10],
       [79, 14]], dtype=int32)>

### Symmetric Matrix

In [51]:
X_sym = np.array([[0,1,2],[1,7,8], [2,8,9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

### Identity Matrix


In [55]:

I = torch.tensor([[1,0,0], [0,1,0], [0,0,1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [56]:
X_pt = torch.tensor([25, 2, 5])
torch.matmul(I, X_pt)

tensor([25,  2,  5])

## Matrix Inversion for Solving the Unknowns

In [57]:
X = np. array([[4,2], [-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [58]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [59]:
y = np.array([4, -7])
y

array([ 4, -7])

In [60]:
w = np.dot(X_inv,y)
w

array([-1.,  4.])

This proves:<br>
<i><b>w</b></i> = <i>X<sup>-1</sup></i>y

### Matrix inversion Where no soln


In [62]:
X= np.array([[4,-1],[4,-1]])
X

array([[ 4, -1],
       [ 4, -1]])

In [63]:
Xinv = np.linalg.inv(X)

LinAlgError: Singular matrix

### Orthogonal Matrices

In [64]:
I = np.array([[1,0, 0],[0,1,0],[0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [65]:
column_1 = I[:,0]
column_1

array([1, 0, 0])

In [66]:
column_2 = I[:,1]
column_2

array([0, 1, 0])

In [67]:
column_3 = I[:,2]
column_3

array([0, 0, 1])

In [68]:
print(np.dot(column_1,column_2))
print(np.dot(column_1,column_3))
print(np.dot(column_2,column_3))

0
0
0


In [70]:
print(np.linalg.norm(column_1))
print(np.linalg.norm(column_2))
print(np.linalg.norm(column_3))

1.0
1.0
1.0


In [71]:
K = torch.tensor([[2/3,1/3,2/3],[-2/3,2/3,1/3],[1/3,2/3,-2/3]])
K

tensor([[ 0.6667,  0.3333,  0.6667],
        [-0.6667,  0.6667,  0.3333],
        [ 0.3333,  0.6667, -0.6667]])

In [72]:
Kcol_1 = K[:,0]

In [73]:
Kcol_2 = K[:,1]

In [74]:
Kcol_3 = K[:,2]

In [77]:
print(torch.dot(Kcol_1,Kcol_2))
print(torch.dot(Kcol_1,Kcol_3))
print(torch.dot(Kcol_2,Kcol_3))

tensor(0.)
tensor(0.)
tensor(0.)


In [78]:
print(torch.norm(Kcol_1))
print(torch.norm(Kcol_2))
print(torch.norm(Kcol_3))

tensor(1.)
tensor(1.)
tensor(1.)


In [80]:
torch.matmul(K.T, K)

tensor([[ 1.0000e+00, -3.3114e-09,  3.3114e-09],
        [-3.3114e-09,  1.0000e+00,  6.6227e-09],
        [ 3.3114e-09,  6.6227e-09,  1.0000e+00]])